package be.davidopdebeeck.bitvavo.client.api.asset;

public class BitvavoAssetSymbols {
    public static BitvavoAssetSymbol EUR = BitvavoAssetSymbol.symbol("EUR");
    public static BitvavoAssetSymbol USDC = BitvavoAssetSymbol.symbol("USDC");
    public static BitvavoAssetSymbol DAI = BitvavoAssetSymbol.symbol("DAI");
    public static BitvavoAssetSymbol AAVE = BitvavoAssetSymbol.symbol("AAVE");
    public static BitvavoAssetSymbol ADA = BitvavoAssetSymbol.symbol("ADA");
    public static BitvavoAssetSymbol ANT = BitvavoAssetSymbol.symbol("ANT");
    public static BitvavoAssetSymbol ARK = BitvavoAssetSymbol.symbol("ARK");
    public static BitvavoAssetSymbol BAND = BitvavoAssetSymbol.symbol("BAND");
    public static BitvavoAssetSymbol BTC = BitvavoAssetSymbol.symbol("BTC");
    public static BitvavoAssetSymbol ENJ = BitvavoAssetSymbol.symbol("ENJ");
    public static BitvavoAssetSymbol ETH = BitvavoAssetSymbol.symbol("ETH");
    public static BitvavoAssetSymbol GAS = BitvavoAssetSymbol.symbol("GAS");
    public static BitvavoAssetSymbol HOT = BitvavoAssetSymbol.symbol("HOT");
    public static BitvavoAssetSymbol IOST = BitvavoAssetSymbol.symbol("IOST");
    public static BitvavoAssetSymbol KMD = BitvavoAssetSymbol.symbol("KMD");
    public static BitvavoAssetSymbol LINK = BitvavoAssetSymbol.symbol("LINK");
    public static BitvavoAssetSymbol LOOM = BitvavoAssetSymbol.symbol("LOOM");
    public static BitvavoAssetSymbol LTC = BitvavoAssetSymbol.symbol("LTC");
    public static BitvavoAssetSymbol MANA = BitvavoAssetSymbol.symbol("MANA");
    public static BitvavoAssetSymbol NPXS = BitvavoAssetSymbol.symbol("NPXS");
    public static BitvavoAssetSymbol NULS = BitvavoAssetSymbol.symbol("NULS");
    public static BitvavoAssetSymbol OGN = BitvavoAssetSymbol.symbol("OGN");
    public static BitvavoAssetSymbol ONG = BitvavoAssetSymbol.symbol("ONG");
    public static BitvavoAssetSymbol ONT = BitvavoAssetSymbol.symbol("ONT");
    public static BitvavoAssetSymbol OXT = BitvavoAssetSymbol.symbol("OXT");
    public static BitvavoAssetSymbol POWR = BitvavoAssetSymbol.symbol("POWR");
    public static BitvavoAssetSymbol PUNDIX = BitvavoAssetSymbol.symbol("PUNDIX");
    public static BitvavoAssetSymbol STEEM = BitvavoAssetSymbol.symbol("STEEM");
    public static BitvavoAssetSymbol STMX = BitvavoAssetSymbol.symbol("STMX");
    public static BitvavoAssetSymbol STORJ = BitvavoAssetSymbol.symbol("STORJ");
    public static BitvavoAssetSymbol STRAX = BitvavoAssetSymbol.symbol("STRAX");
    public static BitvavoAssetSymbol TRX = BitvavoAssetSymbol.symbol("TRX");
    public static BitvavoAssetSymbol VET = BitvavoAssetSymbol.symbol("VET");
    public static BitvavoAssetSymbol XTZ = BitvavoAssetSymbol.symbol("XTZ");
    public static BitvavoAssetSymbol YFI = BitvavoAssetSymbol.symbol("YFI");
    public static BitvavoAssetSymbol ZRX = BitvavoAssetSymbol.symbol("ZRX");
}
